### PR TITLE
Python BBL

### PR DESCRIPTION
**Pull request by pavankumarraju13**

### CODE REVIEW

**Comment by vickyrules** [comment]
@pavankumarraju13 
Plagiarized content:
https://www.geeksforgeeks.org/python-program-for-binary-search/
⚠️Strike -1

**Comment by pavankumarraju13** [comment]
> @pavankumarraju13 Plagiarized content: https://www.geeksforgeeks.org/python-program-for-binary-search/ ⚠️Strike -1

@vickyrules  you didnot said the code should be unique so i added the file
can you remove strike and it would better to make readme file and mention rules.

**Comment by vickyrules** [comment]
@pavankumarraju13 it's obvious, contribution doesn't mean you copy from somewhere and just paste the code. It's should your own code

**Comment by vickyrules** [comment]
@pavankumarraju13 removing strike now, keep in mind for the next time.

**Pull request closed without merging**
